// Importing the Metadata type from Next.js for defining metadata properties
import type { Metadata } from "next";

// Importing custom fonts (Geist Sans and Geist Mono) from Google Fonts using Next.js's font optimization
import { Geist, Geist_Mono } from "next/font/google";

// Importing global CSS styles for the entire application
import "./globals.css";

// Setting up Geist Sans font with a custom CSS variable and limiting to Latin subset
const geistSans = Geist({
  variable: "--font-geist-sans", // CSS variable for Geist Sans font
  subsets: ["latin"], // Subset of the font to be used
});

// Setting up Geist Mono font with a custom CSS variable and limiting to Latin subset
const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // CSS variable for Geist Mono font
  subsets: ["latin"], // Subset of the font to be used
});

// Defining metadata for the application, including the title and description
export const metadata: Metadata = {
  title: "Create Next App", // Page title
  description: "Generated by create next app", // Meta description for SEO
};

// Root layout component for the application
export default function RootLayout({
  children, // React children (content that will be rendered inside the layout)
}: Readonly<{
  children: React.ReactNode; // Type definition for children prop
}>) {
  return (
    <html lang="en" className="light"> {/* Root HTML element with language set to English and a default "light" theme */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} // Applying font variables and enabling antialiasing for better text rendering
      >
        {children} {/* Render the children passed to the RootLayout */}
      </body>
    </html>
  );
}
